require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
    Max: 120

# --- Rubocop RSpec Configuration ---

# Allow Capybara "Gherkin" RSpec DSL
RSpec/Capybara/FeatureMethods:
  Enabled: false
