# require is being deprecated: https://docs.rubocop.org/rubocop/plugin_migration_guide.html
require:
  - rubocop-capybara

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

# --- Rubocop RSpec Configuration ---
RSpec/MultipleExpectations:
  Max: 3

# RSpec/Dialect defaults to allowing all aliases (e.g. Capybara "Gherkin")
