require:
  - rubocop-capybara
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

# --- Rubocop RSpec Configuration ---
RSpec/MultipleExpectations:
  Max: 3

# Allow Capybara "Gherkin" RSpec DSL
RSpec/Capybara/FeatureMethods:
  Enabled: false
