require:
  - rubocop-capybara
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

# --- Rubocop RSpec Configuration ---

# Allow Capybara "Gherkin" RSpec DSL
RSpec/Capybara/FeatureMethods:
  Enabled: false
