require:
  - rubocop-capybara
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

# --- Rubocop RSpec Configuration ---
RSpec/MultipleExpectations:
  Max: 3

# RSpec/Dialect defaults to allowing all aliases (e.g. Capybara "Gherkin")
