version: '3.4'
services:
  browsertests:
    image: brianjbayer/sample-login-capybara-rspec:${BROWSERTESTS_TAG:-latest}
    container_name: ${BROWSERTESTS_HOSTNAME:-browsertests}
    environment:
      - BASE_URL
      - LOGIN_USERNAME
      - LOGIN_PASSWORD
