name: Check Deployable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Use Docker Buildkit for builds
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  BROWSERTESTS_IMAGE: app

jobs:

  code-standards-rubocop:
    runs-on: ubuntu-latest
    env:
      DEVENV: devenv
      BROWSERTESTS_IMAGE: app-devenv

    steps:
      - uses: actions/checkout@v1
      - name: Docker version
        run: docker --version

      - name: Build app development environment
        run: "docker build --no-cache --target ${DEVENV} -t ${BROWSERTESTS_IMAGE} ."

      - name: Run linting script in dev environment image
        run: ./script/dockercomposerun  -n -d ./script/runlint

  security-scan-bundler-audit:
    runs-on: ubuntu-latest
    env:
      DEVENV: devenv
      BROWSERTESTS_IMAGE: app-devenv

    steps:
      - uses: actions/checkout@v1
      - name: Docker version
        run: docker --version

      - name: Build app development environment
        run: "docker build --no-cache --target ${DEVENV} -t ${BROWSERTESTS_IMAGE} ."

      - name: Run security scanning script in dev environment image
        run:  ./script/dockercomposerun -n -d ./script/runsecscan

  build-deploy:
    needs: [code-standards-rubocop, security-scan-bundler-audit]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: docker version
        run: docker --version

      - name: Build app deploy
        run: docker build --no-cache -t ${BROWSERTESTS_IMAGE} .

  run-tests-default-chrome:
    needs: build-deploy
    runs-on: ubuntu-latest
    env:
      LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
      LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

    steps:
      - uses: actions/checkout@v1

      - name: Build app deploy
        run: docker build --no-cache -t ${BROWSERTESTS_IMAGE} .

      - name: dockercomposerun (Run tests) with defaults
        run: ./script/dockercomposerun -c

  run-tests-specified-firefox:
    needs: build-deploy
    runs-on: ubuntu-latest
    env:
      BROWSER: firefox
      SELENIUM_IMAGE: selenium/standalone-firefox:latest
      LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
      LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

    steps:
      - uses: actions/checkout@v1

      - name: Build app deploy
        run: docker build --no-cache -t ${BROWSERTESTS_IMAGE} .

      - name: dockercomposerun (Run tests) with Firefox
        run: ./script/dockercomposerun -c

  run-tests-specified-edge:
    needs: build-deploy
    runs-on: ubuntu-latest
    env:
      BROWSER: edge
      SELENIUM_IMAGE: selenium/standalone-edge:latest
      LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
      LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}

    steps:
      - uses: actions/checkout@v1

      - name: Build app deploy
        run: docker build --no-cache -t ${BROWSERTESTS_IMAGE} .

      - name: dockercomposerun (Run tests) with Edge
        run: ./script/dockercomposerun -c
